### ISSUE TITLE
Unable to install tap 0.28.10-1

### ISSUE THREAD

**Issue by Giom-fm** [hwittenborn/tap#30]
I am trying to install Tap. Unfortunately makedeb fails at the last step.

makedeb version: 8.5.9-1
tap version: 0.28.10-1

Pulling master and trying to build tap by executing `makdeb -si --verbose`.
It fails on the installation step:

```
[#] Installing tap...
+ sudo apt-get reinstall -- ./tap_8.5.9-1_all.deb
Paketlisten werden gelesen… Fertig
E: Nicht unterstützte Datei ./tap_8.5.9-1_all.deb auf Befehlszeile angegeben.
```
The error says something like "Unsupported file specified on command line".
Executing  `sudo apt-get reinstall -- ./tap_8.5.9-1_all.deb` manually works fine for me.

**Comment by hwittenborn** [comment]
This is due to any issue in makedeb, which is being tracked [here](https://github.com/makedeb/makedeb/issues/65). The issue appears to be that makedeb is using an incorrect variable name when generating the filename to install the APT package with, with that being makedeb's current version instead of the package's.

**Comment by Giom-fm** [comment]
Ok got it.
Thank you!

**Comment by hwittenborn** [comment]
Just fyi, but this should be fixed in the latest versions of makedeb. Lmk if you still have issues or anything :)
